[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd php-src/public && php -S 0.0.0.0:$PORT"
