<template>
  <div>
    <section class="relative overflow-hidden">
      <div class="absolute inset-0 mesh-surface"></div>
      <div class="relative max-w-7xl mx-auto px-6 py-28">
        <h1 class="text-5xl md:text-6xl font-semibold leading-tight">
          {{ c?.hero?.title || 'Applicants.io' }}
        </h1>
        <p class="mt-4 text-lg max-w-2xl opacity-90">
          {{ c?.hero?.subtitle || 'AI-Powered Recruiting. Fully Managed.' }}
        </p>
        <div class="mt-8 space-x-4">
          <NuxtLink :to="c?.hero?.primaryCTA?.href || '/contact'" class="px-5 py-3 rounded bg-primary text-black font-medium">{{ c?.hero?.primaryCTA?.text || 'Book a Demo' }}</NuxtLink>
          <NuxtLink :to="c?.hero?.secondaryCTA?.href || '#pricing'" class="px-5 py-3 rounded border border-white/20">{{ c?.hero?.secondaryCTA?.text || 'See Pricing' }}</NuxtLink>
        </div>
      </div>
    </section>
      
    <!-- compose remaining sections as already generated by Cursor -->
    <TrustBar />
    <FeaturesGrid />
    <HowItWorks />
    <WhyChooseUs />
    <IntegrationsBar />
    <ReviewsStrip />
    <Pricing />
    <FAQ />
    <CTA />
  </div>
</template>

<script setup lang="ts">
const c = useLandingContent?.() // safe if composable exists

// SEO meta
useSeoMeta({
  title: 'Applicants.io – AI-Powered Recruiting. Fully Managed.',
  description: 'From job boards to career sites, CRM, automations, SEO, and employer branding — Applicants.io runs your entire hiring engine.',
  ogTitle: 'Applicants.io – AI-Powered Recruiting. Fully Managed.',
  ogDescription: 'From job boards to career sites, CRM, automations, SEO, and employer branding — Applicants.io runs your entire hiring engine.',
  ogImage: '/og-image.png',
  twitterCard: 'summary_large_image',
  twitterTitle: 'Applicants.io – AI-Powered Recruiting. Fully Managed.',
  twitterDescription: 'From job boards to career sites, CRM, automations, SEO, and employer branding — Applicants.io runs your entire hiring engine.',
  twitterImage: '/og-image.png'
})
</script>
